# Generated by Django 5.2.3 on 2025-06-29 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField(default=0)),
                ('wasm', models.BinaryField(max_length=10485760)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catics_core.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player1_id', models.PositiveBigIntegerField()),
                ('player2_id', models.PositiveBigIntegerField()),
                ('is_p1_turn', models.BooleanField(default=True)),
                ('n_kittens_p1', models.PositiveIntegerField(default=8)),
                ('n_cats_p1', models.PositiveIntegerField(default=0)),
                ('n_kittens_p2', models.PositiveIntegerField(default=8)),
                ('n_cats_p2', models.PositiveIntegerField(default=0)),
                ('board', models.JSONField(default=dict)),
                ('promotions', models.JSONField(default=list)),
                ('winner', models.CharField(choices=[('n', 'nobody'), ('1', 'player 1'), ('2', 'player 2')], default='n', max_length=1)),
                ('player1_type', models.ForeignKey(limit_choices_to={'model__in': ['user', 'agentversion']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_player1', to='contenttypes.contenttype')),
                ('player2_type', models.ForeignKey(limit_choices_to={'model__in': ['user', 'agentversion']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_player2', to='contenttypes.contenttype')),
            ],
        ),
    ]
