#!/usr/bin/env python3

import sys
from argparse import ArgumentParser
from getpass import getpass
import requests
from config import Config

parser = ArgumentParser()
parser.add_argument('username')
parser.add_argument('email')
args = parser.parse_args()

password = getpass('password:')

config = Config()

response = requests.post(config['instance'] + '/auth/register/', {
    'username': args.username,
    'email': args.email,
    'password': password,
})


if response.status_code != 200:
    print(response.text, file=sys.stderr)
    exit(1)

config.set(token=response.json()['token'], username=args.username)
config.save()
print("n'oubliez pas de valider votre adresse email 🙂")
