#!/usr/bin/env python3

import hashlib
import random
import string
import sys
from argparse import ArgumentParser
from getpass import getpass
import requests
from config import Config

parser = ArgumentParser()
parser.add_argument('username')
parser.add_argument('email')
args = parser.parse_args()

password = getpass('password:')

config = Config()

response = requests.get(config['instance'] + '/auth/register-challenge/', {
    'email': args.email,
})

if response.status_code != 200:
    print(response.text, file=sys.stderr)
    exit(1)

print('Solving the challenge (this may take a minute)...')

data = response.json()
challenge_id = data['id']
challenge_token = data['challenge']
while True:
    challenge_answer = ''.join(
            random.choice(string.ascii_lowercase)
            for _ in range(6)
        )
    digest = hashlib.sha256((challenge_token + challenge_answer).encode()).hexdigest()
    if digest.startswith("000000"):
        break

response = requests.post(config['instance'] + '/auth/register/', {
    'username': args.username,
    'email': args.email,
    'password': password,
    'challenge_id': challenge_id,
    'challenge_answer': challenge_answer,
})

if response.status_code != 200:
    print(response.text, file=sys.stderr)
    exit(1)

config.set(token=response.json()['token'], username=args.username)
config.save()
print("n'oubliez pas de valider votre adresse email 🙂")
