#!/usr/bin/env python3

from argparse import ArgumentParser
from config import Config

parser = ArgumentParser()
parser.add_argument('url')
args = parser.parse_args()

config = Config()
config.set(instance=args.url)
config.save()

