# Generated by Django 5.2.3 on 2025-06-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catics_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expire_at', models.DateTimeField()),
                ('challenge', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
