# Generated by Django 5.2.3 on 2025-06-29 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catics_auth', '0002_registerchallenge'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='Validation',
        ),
    ]
